#! /bin/bash
# EXECUTED FROM INSIDE DOCKER
set -euf -o pipefail -x
export RUST_BACKTRACE=1

# TODO: try all combinations of features in a nicer way
cargo build --all --all-features
cargo build --examples --all --all-features 
cargo test --all --all-features

# bus without journal
cargo build --all --no-default-features --features bus
cargo test --all --no-default-features --features bus

# journal without bus
cargo build --all --no-default-features --features journal
cargo test --all --no-default-features --features journal

# neither
cargo build --all --no-default-features
cargo test --all --no-default-features

cargo fmt --all -- --check
