on:
  push:
    branches:
      - 'master'
      - 'staging'
      - 'trying'
  pull_request:

name: build

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@beta
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all --all-targets --all-features -- -D warnings

  features:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@beta
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev
      - name: Check with all variants
        run: cargo hack --feature-powerset --skip unstable-doc-cfg check --workspace --all-targets

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev
      - uses: taiki-e/install-action@cargo-hack
      - name: Build everything
        run: cargo hack --feature-powerset --skip unstable-doc-cfg build --all --all-targets
        if: matrix.rust != 'nightly'

      - name: Run all tests
        run: cargo hack --feature-powerset --skip unstable-doc-cfg test --all
        if: matrix.rust != 'nightly'

      - name: Build everything
        run: cargo hack --feature-powerset build --all --all-targets
        if: matrix.rust == 'nightly'

      - name: Run all tests
        run: cargo hack --feature-powerset test --all
        if: matrix.rust == 'nightly'
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
      - run: cargo hack check --rust-version --workspace --all-targets --ignore-private
