on:
  push:
    branches:
      - 'master'
      - 'staging'
      - 'trying'
  pull_request:

name: build

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  features:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev

      - name: Install cargo-hack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-hack

      - name: Check with all variants
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: --feature-powerset --skip unstable-doc-cfg check --workspace --all-targets

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.47.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev

      - name: Install cargo-hack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-hack

      - name: Build everything
        uses: actions-rs/cargo@v1
        if: ${{matrix.rust != 'nightly' }}
        with:
          command: hack
          args: --feature-powerset --skip unstable-doc-cfg build --all --all-targets

      - name: Run all tests
        uses: actions-rs/cargo@v1
        if: ${{matrix.rust != 'nightly' }}
        with:
          command: hack
          args: --feature-powerset --skip unstable-doc-cfg test --all

      - name: Build everything
        uses: actions-rs/cargo@v1
        if: ${{matrix.rust == 'nightly' }}
        with:
          command: hack
          args: --feature-powerset build --all --all-targets

      - name: Run all tests
        uses: actions-rs/cargo@v1
        if: ${{matrix.rust == 'nightly' }}
        with:
          command: hack
          args: --feature-powerset test --all
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack
    - uses: Swatinem/rust-cache@v2
    - run: cargo hack check --rust-version --workspace --all-targets --ignore-private
